#!/usr/bin/env python3
"""Gate (f) checker -- Caracal v2, decision D1.

Gate (f) claims: a vectors-off build is identical to the re-baselined reference
"except for the enumerated encoding widths". This script is what makes that claim
falsifiable rather than asserted.

    gate-f-check.py --pre <dir> --post <dir>     # the gate
    gate-f-check.py --manifest <dir> --out f.json # fingerprint one artifact

<dir> is either a gen-collateral directory or its parent (per-config trees are
found automatically).

WHY THIS IS NOT A TEXTUAL DIFF
------------------------------
Widening `MicroOp.dst_rtype` 2b->3b renumbers every bit position downstream of it
in every bundle that packs a MicroOp -- ROB entries, issue slots, queue payloads.
A line-by-line diff therefore reports thousands of changed subscripts that are all
consequences of the enumerated exception, and drowns the one line that would
matter. So the check is split:

  TIER 1 (strict, the majority of modules)
      A module mentioning neither `rtype` nor `iq_type` cannot be affected by the
      exception. Its normalized text must be EQUAL. Any difference is a violation.

  TIER 2 (structural, the modules that carry the widened fields)
      Text is expected to differ. What must NOT differ is the module's shape:
      same ports, same submodule instances, same statement counts. Every width
      change must land on an allowlisted name and be exactly the enumerated
      widening. Anything else is a violation.

  MODULE SET (strict)
      Neither side may gain or lose a module. This is the "and no vector logic"
      half of D1, and it is the cheapest, sharpest check in the file.

LIMITATION, stated because a gate that overclaims is worse than no gate:
Tier 2 does not prove semantic equivalence. Logic could in principle be altered
while holding port list, instance list and statement counts fixed. Tier 2 detects
added/removed structure, not rewritten expressions. Tier 1 -- which covers most
modules -- is a true equality check.
"""
import argparse, hashlib, json, os, re, sys
from collections import Counter

# --- the enumerated exception (D1), and nothing else -----------------------
# Names permitted to change width, and the only widening permitted on them.
ALLOWED_WIDEN = [
    (re.compile(r'rtype'),  (2, 3)),   # RT_* fields: dst_rtype, lrs1_rtype, lrs2_rtype
    (re.compile(r'iq_type'), (4, 7)),  # IQ_SZ 4 -> 7 (as a packed vector, if packed)
]
# Names permitted to APPEAR on the post side only.
# iq_type is Vec(IQ_SZ, Bool()) so it flattens to iq_type_0..N: 4 -> 7 means
# iq_type_4, _5, _6 are new signals rather than a width change.
ALLOWED_NEW = re.compile(r'iq_type(_\d+)?$|iq_type_\d+_')
TOUCHED_TOKEN = re.compile(r'rtype|iq_type')

# --- normalization ---------------------------------------------------------
RE_LOCATOR = re.compile(r'\s*//\s*@\[[^\]]*\]')      # trailing source locator comment
RE_LOCATOR_INLINE = re.compile(r'@\[[^\]]*\]')       # any residual locator
RE_BANNER = re.compile(r'^// Generated by CIRCT firtool-.*$')
RE_SCALA_STR = re.compile(r'"[^"]*\.scala:[^"]*"')   # assertion text embeds file:line
RE_WS = re.compile(r'[ \t]+')


def normalize(text):
    out = []
    for ln in text.split('\n'):
        if RE_BANNER.match(ln):
            continue
        ln = RE_LOCATOR.sub('', ln)
        ln = RE_LOCATOR_INLINE.sub('', ln)
        ln = RE_SCALA_STR.sub('"<msg>"', ln)
        ln = RE_WS.sub(' ', ln).strip()
        if ln:
            out.append(ln)
    return '\n'.join(out)


# --- structural extraction ------------------------------------------------
RE_DECL = re.compile(
    r'^(?:input|output|inout|wire|reg|logic)\b\s*'
    r'(?:\[\s*(\d+)\s*:\s*(\d+)\s*\]\s*)?'
    r'(\w+)')
RE_INST = re.compile(r'^([A-Z]\w*)\s+(\w+)\s*\($')
RE_STMT = re.compile(r'\b(always_ff|always_comb|always|assign|initial|case|casez)\b')


def shape(norm):
    """Port/decl widths, submodule instances, statement histogram."""
    decls, insts, stmts = {}, Counter(), Counter()
    for ln in norm.split('\n'):
        m = RE_DECL.match(ln)
        if m:
            hi, lo, name = m.group(1), m.group(2), m.group(3)
            decls[name] = (int(hi) - int(lo) + 1) if hi is not None else 1
        m = RE_INST.match(ln)
        if m:
            insts[m.group(1) + ' ' + m.group(2)] += 1
        for k in RE_STMT.findall(ln):
            stmts[k] += 1
    return decls, insts, stmts


def find_collateral(root):
    """Map config-name -> gen-collateral dir under root (or root itself)."""
    root = os.path.abspath(root)
    if os.path.basename(root) == 'gen-collateral':
        return {os.path.basename(os.path.dirname(root)): root}
    found = {}
    if os.path.isdir(os.path.join(root, 'gen-collateral')):
        found[os.path.basename(root)] = os.path.join(root, 'gen-collateral')
        return found
    for d in sorted(os.listdir(root)):
        gc = os.path.join(root, d, 'gen-collateral')
        if os.path.isdir(gc):
            found[d] = gc
    return found


def load_modules(gc):
    """basename(no ext) -> normalized text, for generated Verilog only."""
    mods = {}
    for fn in sorted(os.listdir(gc)):
        if not fn.endswith(('.sv', '.v')):
            continue
        path = os.path.join(gc, fn)
        if not os.path.isfile(path):
            continue
        with open(path, errors='replace') as f:
            mods[fn] = normalize(f.read())
    return mods


# --- modes ----------------------------------------------------------------
def do_manifest(root, label, repo_sha, boom_sha, out):
    man = {'label': label, 'repo_sha': repo_sha, 'boom_sha': boom_sha, 'configs': {}}
    trees = find_collateral(root)
    if not trees:
        sys.exit('no gen-collateral tree found under %s' % root)
    for cfg, gc in trees.items():
        mods = load_modules(gc)
        man['configs'][cfg] = {
            'module_count': len(mods),
            'tree_sha256': hashlib.sha256(
                ''.join(k + '\0' + v for k, v in sorted(mods.items())).encode()
            ).hexdigest(),
            'modules': {k: hashlib.sha256(v.encode()).hexdigest()[:16]
                        for k, v in sorted(mods.items())},
        }
        print('   %-46s %4d modules  tree=%s'
              % (cfg, len(mods), man['configs'][cfg]['tree_sha256'][:12]))
    if out:
        os.makedirs(os.path.dirname(out), exist_ok=True)
        # Carry over configs that exist in the manifest but were not rebuilt this
        # run, so a CONFIGS=<one> re-run cannot quietly shrink a complete manifest.
        if os.path.exists(out):
            try:
                prev = json.load(open(out))
            except ValueError:
                prev = {}
            if prev.get('boom_sha') == boom_sha:
                for cfg, v in prev.get('configs', {}).items():
                    if cfg not in man['configs']:
                        man['configs'][cfg] = v
                        print('   %-46s carried over from previous run' % cfg)
            elif prev.get('configs'):
                print('   NOTE: previous manifest was for boom %s; not carrying its '
                      'configs over' % str(prev.get('boom_sha'))[:12])
        with open(out, 'w') as f:
            json.dump(man, f, indent=1, sort_keys=True)
            f.write('\n')
    return 0


def classify_width(name, pre_w, post_w):
    """Is this width change the enumerated exception? Returns None if OK, else why not."""
    for pat, (a, b) in ALLOWED_WIDEN:
        if pat.search(name):
            if pre_w == a and post_w == b:
                return None
            return ('%s: allowlisted name but width %d->%d is not the enumerated %d->%d'
                    % (name, pre_w, post_w, a, b))
    return '%s: width %d->%d on a name outside the enumerated exception' % (name, pre_w, post_w)


def do_gate(pre_root, post_root, verbose):
    pre_trees, post_trees = find_collateral(pre_root), find_collateral(post_root)
    common = sorted(set(pre_trees) & set(post_trees))
    if not common:
        sys.exit('no config trees in common:\n  pre : %s\n  post: %s'
                 % (sorted(pre_trees), sorted(post_trees)))
    for only in sorted(set(pre_trees) ^ set(post_trees)):
        print('NOTE: config present on only one side, skipped: %s' % only)

    total_v = 0
    for cfg in common:
        pre, post = load_modules(pre_trees[cfg]), load_modules(post_trees[cfg])
        violations, allowed = [], []

        # -- MODULE SET (strict) --
        for m in sorted(set(post) - set(pre)):
            violations.append(('module-added', m, 'module exists only in post -- '
                               'gate (f) forbids new logic in a vectors-off build'))
        for m in sorted(set(pre) - set(post)):
            violations.append(('module-removed', m, 'module exists only in pre'))

        t1 = t1_diff = t2 = 0
        for m in sorted(set(pre) & set(post)):
            a, b = pre[m], post[m]
            touched = bool(TOUCHED_TOKEN.search(a) or TOUCHED_TOKEN.search(b))
            if not touched:
                # -- TIER 1 (strict) --
                t1 += 1
                if a != b:
                    t1_diff += 1
                    violations.append(('tier1-differs', m,
                                       'module mentions neither rtype nor iq_type, so the '
                                       'enumerated exception cannot explain any change'))
                continue
            # -- TIER 2 (structural) --
            t2 += 1
            da, ia, sa = shape(a)
            db, ib, sb = shape(b)
            for name in sorted(set(db) - set(da)):
                if ALLOWED_NEW.search(name):
                    allowed.append((m, 'new signal %s (IQ_SZ 4->7)' % name))
                else:
                    violations.append(('signal-added', m,
                                       'new signal %s outside the enumerated exception' % name))
            for name in sorted(set(da) - set(db)):
                violations.append(('signal-removed', m, 'signal %s disappeared' % name))
            for name in sorted(set(da) & set(db)):
                if da[name] != db[name]:
                    why = classify_width(name, da[name], db[name])
                    if why:
                        violations.append(('width-change', m, why))
                    else:
                        allowed.append((m, '%s %db->%db' % (name, da[name], db[name])))
            if ia != ib:
                d = (ib - ia) + (ia - ib)
                violations.append(('instances-differ', m,
                                   'submodule instances changed: %s'
                                   % ', '.join('%s%+d' % (k, ib[k] - ia[k])
                                               for k in sorted(d))))
            if sa != sb:
                d = set(sa) | set(sb)
                violations.append(('statements-differ', m,
                                   'statement counts changed: %s'
                                   % ', '.join('%s %d->%d' % (k, sa[k], sb[k])
                                               for k in sorted(d) if sa[k] != sb[k])))

        print('\n=== %s ===' % cfg)
        print('  modules            %d (pre) / %d (post)' % (len(pre), len(post)))
        print('  tier 1 strict      %d modules, %d differing' % (t1, t1_diff))
        print('  tier 2 structural  %d modules' % t2)
        print('  allowed deltas     %d (the enumerated exception)' % len(allowed))
        if verbose:
            for m, d in allowed:
                print('      + %-40s %s' % (m, d))
        print('  VIOLATIONS         %d' % len(violations))
        for kind, m, why in violations[:60]:
            print('      ! [%s] %s: %s' % (kind, m, why))
        if len(violations) > 60:
            print('      ... %d more' % (len(violations) - 60))
        total_v += len(violations)

    print('\n%s' % ('GATE (f) PASS -- every difference is the enumerated exception'
                    if total_v == 0 else
                    'GATE (f) FAIL -- %d violation(s)' % total_v))
    return 1 if total_v else 0


def do_verify(root, against, verbose):
    """Did a regeneration reproduce the artifact the manifest records?

    The Verilog is not checked in, so this is how the manifest earns its keep: it
    turns "I regenerated it" into "I regenerated the same thing".
    """
    man = json.load(open(against))
    trees = find_collateral(root)
    bad = 0
    print('manifest %s  (label=%s boom=%s)'
          % (against, man.get('label'), str(man.get('boom_sha'))[:12]))
    for cfg, rec in sorted(man.get('configs', {}).items()):
        if cfg not in trees:
            print('  MISSING  %-46s recorded but no tree on disk' % cfg)
            bad += 1
            continue
        mods = load_modules(trees[cfg])
        got = hashlib.sha256(
            ''.join(k + '\0' + v for k, v in sorted(mods.items())).encode()).hexdigest()
        if got == rec['tree_sha256']:
            print('  ok       %-46s %d modules' % (cfg, len(mods)))
            continue
        bad += 1
        print('  DRIFTED  %-46s recorded %s got %s'
              % (cfg, rec['tree_sha256'][:12], got[:12]))
        rm, gm = rec['modules'], {k: hashlib.sha256(v.encode()).hexdigest()[:16]
                                  for k, v in mods.items()}
        for m in sorted(set(gm) - set(rm)):
            print('             + %s (not in manifest)' % m)
        for m in sorted(set(rm) - set(gm)):
            print('             - %s (in manifest, absent on disk)' % m)
        diff = sorted(m for m in set(rm) & set(gm) if rm[m] != gm[m])
        for m in diff[:20]:
            print('             ~ %s' % m)
        if len(diff) > 20:
            print('             ~ ... %d more changed' % (len(diff) - 20))
    for cfg in sorted(set(trees) - set(man.get('configs', {}))):
        print('  EXTRA    %-46s on disk but not in the manifest' % cfg)
    print('\n%s' % ('VERIFY OK -- trees match the manifest' if not bad
                    else 'VERIFY FAIL -- %d config(s) missing or drifted' % bad))
    return 1 if bad else 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--pre'); ap.add_argument('--post')
    ap.add_argument('--verify'); ap.add_argument('--against')
    ap.add_argument('--manifest'); ap.add_argument('--out')
    ap.add_argument('--label', default=''); ap.add_argument('--repo-sha', default='')
    ap.add_argument('--boom-sha', default=''); ap.add_argument('-v', '--verbose',
                                                              action='store_true')
    a = ap.parse_args()
    if a.manifest:
        return do_manifest(a.manifest, a.label, a.repo_sha, a.boom_sha, a.out)
    if a.verify:
        if not a.against:
            ap.error('--verify needs --against <manifest.json>')
        return do_verify(a.verify, a.against, a.verbose)
    if a.pre and a.post:
        return do_gate(a.pre, a.post, a.verbose)
    ap.error('need --manifest, --verify/--against, or both --pre and --post')


if __name__ == '__main__':
    sys.exit(main())
