#!/usr/bin/env bash
# Self-test for gate-f-check.py.
#
# A gate that cannot fail is worse than no gate: it reports PASS forever and
# nobody notices. This builds synthetic pre/post trees exercising every
# violation class and every permitted delta, and asserts the checker's verdict
# on each. Run it after touching gate-f-check.py.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
T=$(mktemp -d); trap 'rm -rf "$T"' EXIT
PRE="$T/pre/cfg/gen-collateral"; POST="$T/post/cfg/gen-collateral"
mkdir -p "$PRE" "$POST"
fail=0

emit() {  # emit <dir> <module> <body...>
  local d=$1 m=$2; shift 2
  { echo "// Generated by CIRCT firtool-1.75.0"
    echo "module $m(	// @[src/main/scala/Foo.scala:10:7]"
    printf '%s\n' "$@"
    echo "endmodule"; } > "$d/$m.sv"
}

# --- 1. untouched module, identical  -> tier 1, no violation
for d in "$PRE" "$POST"; do
  emit "$d" Untouched "  input clock," "  wire [3:0] x = 4'h5;" "  assign y = x;"
done

# --- 2. untouched module, locators/banner differ only -> normalization must absorb
emit "$PRE"  LocatorOnly "  wire [1:0] a = 2'h1;	// @[Foo.scala:11:3]"
emit "$POST" LocatorOnly "  wire [1:0] a = 2'h1;	// @[Foo.scala:999:77]"

# --- 3. touched module, the ENUMERATED widening -> allowed
emit "$PRE"  Touched "  input [1:0] io_uop_dst_rtype," "  wire [1:0] rtype_q;" "  assign rtype_q = io_uop_dst_rtype;"
emit "$POST" Touched "  input [2:0] io_uop_dst_rtype," "  wire [2:0] rtype_q;" "  assign rtype_q = io_uop_dst_rtype;"

# --- 4. iq_type gaining flattened members 4..6 -> allowed
emit "$PRE"  IqFlat "  input iq_type_0," "  input iq_type_1," "  assign iq_type_z = iq_type_0;"
emit "$POST" IqFlat "  input iq_type_0," "  input iq_type_1," "  input iq_type_4," \
                    "  input iq_type_5," "  input iq_type_6," "  assign iq_type_z = iq_type_0;"

# --- 5. VIOLATION: tier-1 module whose text changed
emit "$PRE"  T1Changed "  wire [3:0] q = 4'h1;"
emit "$POST" T1Changed "  wire [3:0] q = 4'h2;"

# --- 6. VIOLATION: width change on a non-allowlisted name
emit "$PRE"  BadWidth "  input [1:0] io_uop_dst_rtype," "  wire [3:0] unrelated;"
emit "$POST" BadWidth "  input [2:0] io_uop_dst_rtype," "  wire [7:0] unrelated;"

# --- 7. VIOLATION: allowlisted name, but NOT the enumerated widening (2->4)
emit "$PRE"  WrongDelta "  input [1:0] io_uop_lrs1_rtype," "  wire rtype_v;"
emit "$POST" WrongDelta "  input [3:0] io_uop_lrs1_rtype," "  wire rtype_v;"

# --- 8. VIOLATION: new module on the post side (this is "no vector logic")
emit "$POST" VecPipeline "  input clock," "  wire [255:0] vd;"

# --- 9. VIOLATION: touched module gains a submodule instance
emit "$PRE"  GainsInst "  input [1:0] io_uop_dst_rtype," "  Sub sub_0 (" "  );"
emit "$POST" GainsInst "  input [2:0] io_uop_dst_rtype," "  Sub sub_0 (" "  );" \
                       "  VecThing vt_0 (" "  );"

# --- 10. VIOLATION: touched module gains a statement
emit "$PRE"  GainsStmt "  input [1:0] io_uop_dst_rtype," "  assign a = 1'h0;"
emit "$POST" GainsStmt "  input [2:0] io_uop_dst_rtype," "  assign a = 1'h0;" "  assign b = 1'h1;"

# --- 11. VIOLATION: signal removed from a touched module
emit "$PRE"  LosesSig "  input [1:0] io_uop_dst_rtype," "  wire keepme;" "  assign keepme = 1'h0;"
emit "$POST" LosesSig "  input [2:0] io_uop_dst_rtype," "  assign keepme = 1'h0;"

OUT=$("$HERE/gate-f-check.py" --pre "$T/pre" --post "$T/post" -v 2>&1)
echo "$OUT"
echo "--------------------------------------------------------------"

expect_v()  { grep -q "\[$1\].*$2" <<<"$OUT" && echo "  ok   $1 on $2" \
              || { echo "  FAIL expected violation [$1] on $2"; fail=1; }; }
expect_ok() { grep -q "! \[[a-z-]*\] $1" <<<"$OUT" \
              && { echo "  FAIL $1 must NOT be a violation"; fail=1; } \
              || echo "  ok   $1 clean"; }

expect_ok Untouched
expect_ok LocatorOnly
expect_ok Touched
expect_ok IqFlat
expect_v  tier1-differs      T1Changed
expect_v  width-change       BadWidth
expect_v  width-change       WrongDelta
expect_v  module-added       VecPipeline
expect_v  instances-differ   GainsInst
expect_v  statements-differ  GainsStmt
expect_v  signal-removed     LosesSig
grep -q 'GATE (f) FAIL' <<<"$OUT" && echo "  ok   overall verdict FAIL" \
  || { echo "  FAIL overall verdict should be FAIL"; fail=1; }

# and the clean case must PASS
rm -rf "$T/post"; cp -r "$T/pre" "$T/post"
"$HERE/gate-f-check.py" --pre "$T/pre" --post "$T/post" >/dev/null 2>&1 \
  && echo "  ok   identical trees PASS (exit 0)" \
  || { echo "  FAIL identical trees must exit 0"; fail=1; }

echo "--------------------------------------------------------------"
[ $fail -eq 0 ] && echo "selftest: ALL OK" || echo "selftest: FAILURES"
exit $fail
