clear -all
analyze -sv09 -incdir ../HardFloat/source -incdir ../HardFloat/source/RISCV autogen_defines.h \
briscv_defines.h \
../HardFloat/source/RISCV/HardFloat_specialize.v \
../HardFloat/source/HardFloat_primitives.v \
../HardFloat/source/HardFloat_rawFN.v \
../HardFloat/source/addRecFN.v \
../HardFloat/source/compareRecFN.v \
../HardFloat/source/divSqrtRecFN_small.v \
../HardFloat/source/fNToRecFN.v \
../HardFloat/source/iNToRecFN.v \
../HardFloat/source/isSigNaNRecFN.v \
../HardFloat/source/mulAddRecFN.v \
../HardFloat/source/mulRecFN.v \
../HardFloat/source/recFNToFN.v \
../HardFloat/source/recFNToIN.v \
../HardFloat/source/recFNToRecFN.v \
autogen_riscv_imabfv.v \
lrm_assertions.sv \
lrm_model.sv \
tt_ascii_instrn_decode.sv \
tt_briscv_pkg.vh \
tt_cam_buffer.sv \
tt_compare.sv \
tt_decoded_mux.sv \
tt_decoder.sv \
tt_ex.sv \
tt_ffs.sv \
tt_fifo.sv \
tt_id.sv \
tt_lq.sv \
tt_mask_fsm.sv \
tt_mem.sv \
tt_memop_fsm.sv \
tt_pipe_stage.sv \
tt_popcnt.sv \
tt_reshape.sv \
tt_rts_rtr_pipe_stage.sv \
tt_scoreboard_ovi.sv \
tt_skid_buffer.sv \
tt_store_fsm.sv \
tt_vec.sv \
tt_vec_iadd.sv \
tt_vec_idp.sv \
tt_vec_imul.sv \
tt_vec_mul_dp.sv \
tt_vec_regfile.sv \
tt_vfp_encoder.sv \
tt_vfp_encoder_lane.sv \
tt_vfp_ex_unit.sv \
tt_vfp_fma.sv \
tt_vfp_lane.sv \
tt_vfp_red.sv \
tt_vfp_unit.sv \
tt_vpu_ovi.sv \
tt_vpu_ovi_assert.sv
set top tt_vpu_ovi
elaborate -top $top -bbox_mul 256
clock clk
reset !reset_n
